-- Schema for Profile
-- Generated by CIMTool https://cimtool.ucaiug.io

-- A wire or combination of wires, with consistent electrical characteristics,
-- building a single electrical system, used to carry alternating current
-- between points in the power system.
-- For symmetrical, transposed three phase lines, it is sufficient to use
-- attributes of the line segment, which describe impedances and admittances
-- for the entire length of the segment. Additionally impedances can be computed
-- by using length and associated per length impedances.
-- The BaseVoltage at the two ends of ACLineSegments in a Line shall have
-- the same BaseVoltage.nominalVoltage. However, boundary lines may have slightly
-- different BaseVoltage.nominalVoltages and variation is allowed. Larger
-- voltage difference in general requires use of an equivalent branch.
CREATE TABLE "ACLineSegment"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE,
    -- The aggregate flag provides an alternative way of representing an aggregated
    -- (equivalent) element. It is applicable in cases when the dedicated classes
    -- for equivalent equipment do not have all of the attributes necessary to
    -- represent the required level of detail. In case the flag is set to “true”
    -- the single instance of equipment represents multiple pieces of equipment
    -- that have been modelled together as an aggregate equivalent obtained by
    -- a network reduction procedure. Examples would be power transformers or
    -- synchronous machines operating in parallel modelled as a single aggregate
    -- power transformer or aggregate synchronous machine.
    -- The attribute is not used for EquivalentBranch, EquivalentShunt and EquivalentInjection.
    "aggregate" CHAR(1),
    -- The aliasName is free text human readable name of the object alternative
    -- to IdentifiedObject.name. It may be non unique and may not correlate to
    -- a naming hierarchy.
    -- The attribute aliasName is retained because of backwards compatibility
    -- between CIM relases. It is however recommended to replace aliasName with
    -- the Name class as aliasName is planned for retirement at a future time.
    "aliasName" CHAR VARYING(30),
    -- Zero sequence shunt (charging) susceptance, uniformly distributed, of the
    -- entire line section.
    "b0ch" DOUBLE PRECISION,
    -- Positive sequence shunt (charging) susceptance, uniformly distributed,
    -- of the entire line section. This value represents the full charging over
    -- the full length of the line.
    "bch" DOUBLE PRECISION,
    -- The description is a free human readable text describing or naming the
    -- object. It may be non unique and may not correlate to a naming hierarchy.
    "description" CHAR VARYING(30),
    -- Zero sequence shunt (charging) conductance, uniformly distributed, of the
    -- entire line section.
    "g0ch" DOUBLE PRECISION,
    -- Positive sequence shunt (charging) conductance, uniformly distributed,
    -- of the entire line section.
    "gch" DOUBLE PRECISION,
    -- Specifies the availability of the equipment. True means the equipment is
    -- available for topology processing, which determines if the equipment is
    -- energized or not. False means that the equipment is treated by network
    -- applications as if it is not in the model.
    "inService" CHAR(1),
    -- Segment length for calculating line section capabilities.
    "length" DOUBLE PRECISION,
    -- The name is any free human readable and possibly non unique text naming
    -- the object.
    "name" CHAR VARYING(30),
    -- The equipment is enabled to participate in network analysis. If unspecified,
    -- the value is assumed to be true.
    "networkAnalysisEnabled" CHAR(1),
    -- Specifies the availability of the equipment under normal operating conditions.
    -- True means the equipment is available for topology processing, which determines
    -- if the equipment is energized or not. False means that the equipment is
    -- treated by network applications as if it is not in the model.
    "normallyInService" CHAR(1),
    -- Positive sequence series resistance of the entire line section.
    "r" DOUBLE PRECISION,
    -- Zero sequence series resistance of the entire line section.
    "r0" DOUBLE PRECISION,
    -- Maximum permitted temperature at the end of SC for the calculation of minimum
    -- short-circuit currents. Used for short circuit data exchange according
    -- to IEC 60909.
    "shortCircuitEndTemperature" DOUBLE PRECISION,
    -- Positive sequence series reactance of the entire line section.
    "x" DOUBLE PRECISION,
    -- Zero sequence series reactance of the entire line section.
    "x0" DOUBLE PRECISION,
    -- Datasheet information for this power system resource.
    "AssetDatasheet"CHAR VARYING(30),
    -- Base voltage of this conducting equipment. Use only when there is no voltage
    -- level container used and only one base voltage applies. For example, not
    -- used for transformers.
    "BaseVoltage"CHAR VARYING(30),
    -- Container of this equipment.
    "EquipmentContainer"CHAR VARYING(30),
    -- Action involving grounding operation on this conducting equipment.
    "GroundingAction"CHAR VARYING(30),
    -- Dataset containing the data objects.
    "InstanceSet"CHAR VARYING(30),
    -- Jumper action involving jumping operation on this conducting equipment.
    "JumpingAction"CHAR VARYING(30),
    -- Ground action involving clamp usage (for the case when the ground is applied
    -- along the line segment instead of at its terminals).
    "LineGroundingAction"CHAR VARYING(30),
    -- Jumper action involving clamp usage (for the case when the jumper is applied
    -- along the line segment instead of at its terminals).
    "LineJumpingAction"CHAR VARYING(30),
    -- Location of this power system resource.
    "Location"CHAR VARYING(30),
    -- The outage that is isolated by the outage isolation equipment.
    "Outage"CHAR VARYING(30),
    -- Per-length impedance of this line segment.
    "PerLengthImpedance"CHAR VARYING(30),
    -- The single CIM data object in the appropriate dataset context.
    "PropertiesCIMDataObject"CHAR VARYING(30),
    -- Custom classification for this power system resource.
    "PSRType"CHAR VARYING(30),
    -- The wire spacing information that applies to this AC line segment
    "WireSpacingInfo"CHAR VARYING(30)
);

-- Represents a single wire of an alternating current line segment.
CREATE TABLE "ACLineSegmentPhase"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE
);

-- Limit values for Analog measurements.
CREATE TABLE "AnalogLimit"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE,
    -- The value to supervise against.
    "value" DOUBLE PRECISION,
    -- The set of limits.
    "LimitSet"CHAR VARYING(30)
);

-- An AnalogLimitSet specifies a set of Limits that are associated with an
-- Analog measurement.
CREATE TABLE "AnalogLimitSet"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE
);

-- Defines a system base voltage which is referenced.
CREATE TABLE "BaseVoltage"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE
);

-- The parts of a power system that are physical devices, electronic or mechanical.
CREATE TABLE "Equipment"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE,
    -- The aggregate flag provides an alternative way of representing an aggregated
    -- (equivalent) element. It is applicable in cases when the dedicated classes
    -- for equivalent equipment do not have all of the attributes necessary to
    -- represent the required level of detail. In case the flag is set to “true”
    -- the single instance of equipment represents multiple pieces of equipment
    -- that have been modelled together as an aggregate equivalent obtained by
    -- a network reduction procedure. Examples would be power transformers or
    -- synchronous machines operating in parallel modelled as a single aggregate
    -- power transformer or aggregate synchronous machine.
    -- The attribute is not used for EquivalentBranch, EquivalentShunt and EquivalentInjection.
    "aggregate" CHAR(1),
    -- Specifies the availability of the equipment. True means the equipment is
    -- available for topology processing, which determines if the equipment is
    -- energized or not. False means that the equipment is treated by network
    -- applications as if it is not in the model.
    "inService" CHAR(1),
    -- The equipment is enabled to participate in network analysis. If unspecified,
    -- the value is assumed to be true.
    "networkAnalysisEnabled" CHAR(1),
    -- Specifies the availability of the equipment under normal operating conditions.
    -- True means the equipment is available for topology processing, which determines
    -- if the equipment is energized or not. False means that the equipment is
    -- treated by network applications as if it is not in the model.
    "normallyInService" CHAR(1),
    -- Container of this equipment.
    "EquipmentContainer"CHAR VARYING(30)
);

-- A modelling construct to provide a root class for containing equipment.
CREATE TABLE "EquipmentContainer"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE
);

-- A collection of equipment at one common system voltage forming a switchgear.
-- The equipment typically consists of breakers, busbars, instrumentation,
-- control, regulation and protection devices as well as assemblies of all
-- these.
CREATE TABLE "VoltageLevel"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE,
    -- The bus bar's high voltage limit.
    -- The limit applies to all equipment and nodes contained in a given VoltageLevel.
    -- It is not required that it is exchanged in pair with lowVoltageLimit. It
    -- is preferable to use operational VoltageLimit, which prevails, if present.
    "highVoltageLimit" DOUBLE PRECISION,
    -- The bus bar's low voltage limit.
    -- The limit applies to all equipment and nodes contained in a given VoltageLevel.
    -- It is not required that it is exchanged in pair with highVoltageLimit.
    -- It is preferable to use operational VoltageLimit, which prevails, if present.
    "lowVoltageLimit" DOUBLE PRECISION,
    -- The base voltage used for all equipment within the voltage level.
    "BaseVoltage"CHAR VARYING(30),
    -- The substation of the voltage level.
    "Substation"CHAR VARYING(30)
);

-- association constraint
ALTER TABLE "ACLineSegment" ADD FOREIGN KEY ( "AssetDatasheet" ) REFERENCES "AssetInfo" ( "mRID" );
-- association constraint
ALTER TABLE "ACLineSegment" ADD FOREIGN KEY ( "BaseVoltage" ) REFERENCES "BaseVoltage" ( "mRID" );
-- association constraint
ALTER TABLE "ACLineSegment" ADD FOREIGN KEY ( "EquipmentContainer" ) REFERENCES "EquipmentContainer" ( "mRID" );
-- association constraint
ALTER TABLE "ACLineSegment" ADD FOREIGN KEY ( "GroundingAction" ) REFERENCES "GroundAction" ( "mRID" );
-- association constraint
ALTER TABLE "ACLineSegment" ADD FOREIGN KEY ( "InstanceSet" ) REFERENCES "InstanceSet" ( "mRID" );
-- association constraint
ALTER TABLE "ACLineSegment" ADD FOREIGN KEY ( "JumpingAction" ) REFERENCES "JumperAction" ( "mRID" );
-- association constraint
ALTER TABLE "ACLineSegment" ADD FOREIGN KEY ( "LineGroundingAction" ) REFERENCES "GroundAction" ( "mRID" );
-- association constraint
ALTER TABLE "ACLineSegment" ADD FOREIGN KEY ( "LineJumpingAction" ) REFERENCES "JumperAction" ( "mRID" );
-- association constraint
ALTER TABLE "ACLineSegment" ADD FOREIGN KEY ( "Location" ) REFERENCES "Location" ( "mRID" );
-- association constraint
ALTER TABLE "ACLineSegment" ADD FOREIGN KEY ( "Outage" ) REFERENCES "Outage" ( "mRID" );
-- association constraint
ALTER TABLE "ACLineSegment" ADD FOREIGN KEY ( "PerLengthImpedance" ) REFERENCES "PerLengthImpedance" ( "mRID" );
-- association constraint
ALTER TABLE "ACLineSegment" ADD FOREIGN KEY ( "PropertiesCIMDataObject" ) REFERENCES "ChangeSetMember" ( "mRID" );
-- association constraint
ALTER TABLE "ACLineSegment" ADD FOREIGN KEY ( "PSRType" ) REFERENCES "PSRType" ( "mRID" );
-- association constraint
ALTER TABLE "ACLineSegment" ADD FOREIGN KEY ( "WireSpacingInfo" ) REFERENCES "WireSpacingInfo" ( "mRID" );
-- association constraint
ALTER TABLE "AnalogLimit" ADD FOREIGN KEY ( "LimitSet" ) REFERENCES "AnalogLimitSet" ( "mRID" );
-- association constraint
ALTER TABLE "Equipment" ADD FOREIGN KEY ( "EquipmentContainer" ) REFERENCES "EquipmentContainer" ( "mRID" );
-- subclass-superclass constraint
ALTER TABLE "VoltageLevel" ADD FOREIGN KEY ( "mRID" ) REFERENCES "EquipmentContainer" ( "mRID" );
-- association constraint
ALTER TABLE "VoltageLevel" ADD FOREIGN KEY ( "BaseVoltage" ) REFERENCES "BaseVoltage" ( "mRID" );
-- association constraint
ALTER TABLE "VoltageLevel" ADD FOREIGN KEY ( "Substation" ) REFERENCES "Substation" ( "mRID" );
