-- Schema for Profile
-- Generated by CIMTool https://cimtool.ucaiug.io

-- A wire or combination of wires, with consistent electrical characteristics,
-- building a single electrical system, used to carry alternating current
-- between points in the power system.
-- For symmetrical, transposed three phase lines, it is sufficient to use
-- attributes of the line segment, which describe impedances and admittances
-- for the entire length of the segment. Additionally impedances can be computed
-- by using length and associated per length impedances.
-- The BaseVoltage at the two ends of ACLineSegments in a Line shall have
-- the same BaseVoltage.nominalVoltage. However, boundary lines may have slightly
-- different BaseVoltage.nominalVoltages and variation is allowed. Larger
-- voltage difference in general requires use of an equivalent branch.
CREATE TABLE "ACLineSegment"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE,
    -- The aggregate flag provides an alternative way of representing an aggregated
    -- (equivalent) element. It is applicable in cases when the dedicated classes
    -- for equivalent equipment do not have all of the attributes necessary to
    -- represent the required level of detail. In case the flag is set to “true”
    -- the single instance of equipment represents multiple pieces of equipment
    -- that have been modelled together as an aggregate equivalent obtained by
    -- a network reduction procedure. Examples would be power transformers or
    -- synchronous machines operating in parallel modelled as a single aggregate
    -- power transformer or aggregate synchronous machine.
    -- The attribute is not used for EquivalentBranch, EquivalentShunt and EquivalentInjection.
    "aggregate" CHAR(1),
    -- The aliasName is free text human readable name of the object alternative
    -- to IdentifiedObject.name. It may be non unique and may not correlate to
    -- a naming hierarchy.
    -- The attribute aliasName is retained because of backwards compatibility
    -- between CIM relases. It is however recommended to replace aliasName with
    -- the Name class as aliasName is planned for retirement at a future time.
    "aliasName" CHAR VARYING(30),
    -- Zero sequence shunt (charging) susceptance, uniformly distributed, of the
    -- entire line section.
    "b0ch" DOUBLE PRECISION,
    -- Positive sequence shunt (charging) susceptance, uniformly distributed,
    -- of the entire line section. This value represents the full charging over
    -- the full length of the line.
    "bch" DOUBLE PRECISION,
    -- The description is a free human readable text describing or naming the
    -- object. It may be non unique and may not correlate to a naming hierarchy.
    "description" CHAR VARYING(30),
    -- Zero sequence shunt (charging) conductance, uniformly distributed, of the
    -- entire line section.
    "g0ch" DOUBLE PRECISION,
    -- Positive sequence shunt (charging) conductance, uniformly distributed,
    -- of the entire line section.
    "gch" DOUBLE PRECISION,
    -- Specifies the availability of the equipment. True means the equipment is
    -- available for topology processing, which determines if the equipment is
    -- energized or not. False means that the equipment is treated by network
    -- applications as if it is not in the model.
    "inService" CHAR(1),
    -- Segment length for calculating line section capabilities.
    "length" DOUBLE PRECISION,
    -- The name is any free human readable and possibly non unique text naming
    -- the object.
    "name" CHAR VARYING(30),
    -- The equipment is enabled to participate in network analysis. If unspecified,
    -- the value is assumed to be true.
    "networkAnalysisEnabled" CHAR(1),
    -- Specifies the availability of the equipment under normal operating conditions.
    -- True means the equipment is available for topology processing, which determines
    -- if the equipment is energized or not. False means that the equipment is
    -- treated by network applications as if it is not in the model.
    "normallyInService" CHAR(1),
    -- Positive sequence series resistance of the entire line section.
    "r" DOUBLE PRECISION,
    -- Zero sequence series resistance of the entire line section.
    "r0" DOUBLE PRECISION,
    -- Maximum permitted temperature at the end of SC for the calculation of minimum
    -- short-circuit currents. Used for short circuit data exchange according
    -- to IEC 60909.
    "shortCircuitEndTemperature" DOUBLE PRECISION,
    -- Positive sequence series reactance of the entire line section.
    "x" DOUBLE PRECISION,
    -- Zero sequence series reactance of the entire line section.
    "x0" DOUBLE PRECISION,
    -- Datasheet information for this power system resource.
    "AssetDatasheet"CHAR VARYING(30),
    -- Base voltage of this conducting equipment. Use only when there is no voltage
    -- level container used and only one base voltage applies. For example, not
    -- used for transformers.
    "BaseVoltage"CHAR VARYING(30),
    -- Container of this equipment.
    "EquipmentContainer"CHAR VARYING(30),
    -- Action involving grounding operation on this conducting equipment.
    "GroundingAction"CHAR VARYING(30),
    -- Dataset containing the data objects.
    "InstanceSet"CHAR VARYING(30),
    -- Jumper action involving jumping operation on this conducting equipment.
    "JumpingAction"CHAR VARYING(30),
    -- Ground action involving clamp usage (for the case when the ground is applied
    -- along the line segment instead of at its terminals).
    "LineGroundingAction"CHAR VARYING(30),
    -- Jumper action involving clamp usage (for the case when the jumper is applied
    -- along the line segment instead of at its terminals).
    "LineJumpingAction"CHAR VARYING(30),
    -- Location of this power system resource.
    "Location"CHAR VARYING(30),
    -- The outage that is isolated by the outage isolation equipment.
    "Outage"CHAR VARYING(30),
    -- Per-length impedance of this line segment.
    "PerLengthImpedance"CHAR VARYING(30),
    -- The single CIM data object in the appropriate dataset context.
    "PropertiesCIMDataObject"CHAR VARYING(30),
    -- Custom classification for this power system resource.
    "PSRType"CHAR VARYING(30),
    -- The wire spacing information that applies to this AC line segment
    "WireSpacingInfo"CHAR VARYING(30)
);

-- Represents a single wire of an alternating current line segment.
CREATE TABLE "ACLineSegmentPhase"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE
);

-- Limit values for Analog measurements.
CREATE TABLE "AnalogLimit"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE,
    -- The value to supervise against.
    "value" DOUBLE PRECISION,
    -- The set of limits.
    "LimitSet"CHAR VARYING(30)
);

-- An AnalogLimitSet specifies a set of Limits that are associated with an
-- Analog measurement.
CREATE TABLE "AnalogLimitSet"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE
);

-- Tangible resource of the utility, including power system equipment, various
-- end devices, cabinets, buildings, etc. For electrical network equipment,
-- the role of the asset is defined through PowerSystemResource and its subclasses,
-- defined mainly in the Wires model (refer to IEC61970-301 and model package
-- IEC61970::Wires). Asset description places emphasis on the physical characteristics
-- of the equipment fulfilling that role.
CREATE TABLE "Asset"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE
);

-- Set of attributes of an asset, representing typical datasheet information
-- of a physical device that can be instantiated and shared in different data
-- exchange contexts:
-- - as attributes of an asset instance (installed or in stock)
-- - as attributes of an asset model (product by a manufacturer)
-- - as attributes of a type asset (generic type of an asset as used in designs/extension
-- planning).
CREATE TABLE "AssetInfo"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE
);

-- Defines a system base voltage which is referenced.
CREATE TABLE "BaseVoltage"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE
);

-- A CRUD-style data object.
CREATE TABLE "ChangeSetMember"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE
);

-- A Clamp is a galvanic connection at a line segment where other equipment
-- is connected. A Clamp does not cut the line segment.
-- A Clamp is ConductingEquipment and has one Terminal with an associated
-- ConnectivityNode. Any other ConductingEquipment can be connected to the
-- Clamp ConnectivityNode.
CREATE TABLE "Clamp"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE
);

-- Safety document used to authorise work on conducting equipment in the field.
-- Tagged equipment is not allowed to be operated.
CREATE TABLE "ClearanceDocument"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE
);

-- Used to report details on creation, change or deletion of an entity or
-- its configuration.
CREATE TABLE "ConfigurationEvent"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE
);

-- Equipment whose in service status is to change, such as a power transformer
-- or AC line segment.
CREATE TABLE "ContingencyEquipment"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE
);

-- Control is used for supervisory/device control. It represents control outputs
-- that are used to change the state in a process, e.g. close or open breaker,
-- a set point value or a raise lower command.
CREATE TABLE "Control"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE
);

-- A cut separates a line segment into two parts. The cut appears as a switch
-- inserted between these two parts and connects them together. As the cut
-- is normally open there is no galvanic connection between the two line segment
-- parts. But it is possible to close the cut to get galvanic connection.
-- The cut terminals are oriented towards the line segment terminals with
-- the same sequence number. Hence the cut terminal with sequence number equal
-- to 1 is oriented to the line segment's terminal with sequence number equal
-- to 1.
-- The cut terminals also act as connection points for jumpers and other equipment,
-- e.g. a mobile generator. To enable this, connectivity nodes are placed
-- at the cut terminals. Once the connectivity nodes are in place any conducting
-- equipment can be connected at them.
CREATE TABLE "Cut"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE,
    -- The line segment to which the cut is applied.
    "ACLineSegment"CHAR VARYING(30)
);

-- An object that defines one or more points in a given space. This object
-- can be associated with anything that specializes IdentifiedObject. For
-- single line diagrams such objects typically include such items as analog
-- values, breakers, disconnectors, power transformers, and transmission lines.
CREATE TABLE "DiagramObject"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE
);

-- The parts of a power system that are physical devices, electronic or mechanical.
CREATE TABLE "Equipment"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE,
    -- The aggregate flag provides an alternative way of representing an aggregated
    -- (equivalent) element. It is applicable in cases when the dedicated classes
    -- for equivalent equipment do not have all of the attributes necessary to
    -- represent the required level of detail. In case the flag is set to “true”
    -- the single instance of equipment represents multiple pieces of equipment
    -- that have been modelled together as an aggregate equivalent obtained by
    -- a network reduction procedure. Examples would be power transformers or
    -- synchronous machines operating in parallel modelled as a single aggregate
    -- power transformer or aggregate synchronous machine.
    -- The attribute is not used for EquivalentBranch, EquivalentShunt and EquivalentInjection.
    "aggregate" CHAR(1),
    -- Specifies the availability of the equipment. True means the equipment is
    -- available for topology processing, which determines if the equipment is
    -- energized or not. False means that the equipment is treated by network
    -- applications as if it is not in the model.
    "inService" CHAR(1),
    -- The equipment is enabled to participate in network analysis. If unspecified,
    -- the value is assumed to be true.
    "networkAnalysisEnabled" CHAR(1),
    -- Specifies the availability of the equipment under normal operating conditions.
    -- True means the equipment is available for topology processing, which determines
    -- if the equipment is energized or not. False means that the equipment is
    -- treated by network applications as if it is not in the model.
    "normallyInService" CHAR(1),
    -- Container of this equipment.
    "EquipmentContainer"CHAR VARYING(30)
);

-- A modelling construct to provide a root class for containing equipment.
CREATE TABLE "EquipmentContainer"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE
);

-- This represents one instance of an equipment that contributes to the calculation
-- of an operational limit.
CREATE TABLE "EquipmentLimitSeriesComponent"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE
);

CREATE TABLE "EquipmentUnavailabilitySchedule"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE
);

-- Abnormal condition causing current flow through conducting equipment, such
-- as caused by equipment failure or short circuits from objects not typically
-- modelled (for example, a tree falling on a line).
CREATE TABLE "Fault"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE,
    -- Location of this fault.
    "Location"CHAR VARYING(30),
    -- Outage associated with this fault.
    "Outage"CHAR VARYING(30)
);

-- An arbitrary switching step.
CREATE TABLE "GenericAction"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE
);

-- Action on ground as a switching step.
CREATE TABLE "GroundAction"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE
);

-- Instance of a version of a model part. This corresponds to a payload of
-- instance data.
CREATE TABLE "InstanceSet"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE
);

-- Action on jumper as a switching step.
CREATE TABLE "JumperAction"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE
);

-- A limit calculation model used to compute an operational limit based on
-- external input such as temperature. These are intended to be shared among
-- operational limits with the same calculation form that apply to a piece
-- of equipment..
CREATE TABLE "LimitDependency"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE
);

-- A fault that occurs on an AC line segment at some point along the length.
CREATE TABLE "LineFault"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE
);

-- The place, scene, or point of something where someone or something has
-- been, is, and/or will be at a given moment in time. It can be defined with
-- one or more position points (coordinates) in a given coordinate system.
CREATE TABLE "Location"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE
);

-- A Measurement represents any measured, calculated or non-measured non-calculated
-- quantity. Any piece of equipment may contain Measurements, e.g. a substation
-- may have temperature measurements and door open indications, a transformer
-- may have oil temperature and tank pressure measurements, a bay may contain
-- a number of power flow measurements and a Breaker may contain a switch
-- status measurement.
-- The PSR - Measurement association is intended to capture this use of Measurement
-- and is included in the naming hierarchy based on EquipmentContainer. The
-- naming hierarchy typically has Measurements as leaves, e.g. Substation-VoltageLevel-Bay-Switch-Measurement.
-- Some Measurements represent quantities related to a particular sensor location
-- in the network, e.g. a voltage transformer (VT) or potential transformer
-- (PT) at a busbar or a current transformer (CT) at the bar between a breaker
-- and an isolator. The sensing position is not captured in the PSR - Measurement
-- association. Instead it is captured by the Measurement - Terminal association
-- that is used to define the sensing location in the network topology. The
-- location is defined by the connection of the Terminal to ConductingEquipment.
-- If both a Terminal and PSR are associated, and the PSR is of type ConductingEquipment,
-- the associated Terminal should belong to that ConductingEquipment instance.
-- When the sensor location is needed both Measurement-PSR and Measurement-Terminal
-- are used. The Measurement-Terminal association is never used alone.
CREATE TABLE "Measurement"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE
);

-- The Name class provides the means to define any number of human readable
-- names for an object. A name is <b>not</b> to be used for defining inter-object
-- relationships. For inter-object relationships instead use the object identification
-- 'mRID'.
CREATE TABLE "Name"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE
);

-- Specifies the operations contract relationship between a power system resource
-- and a contract participant.
CREATE TABLE "OperatingShare"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE
);

-- A set of limits associated with equipment. Sets of limits might apply to
-- a specific temperature, or season for example. A set of limits may contain
-- different severities of limit levels that would apply to the same equipment.
-- The set may contain limits of different types such as apparent power and
-- current limits or high and low voltage limits that are logically applied
-- together as a set.
CREATE TABLE "OperationalLimitSet"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE
);

-- A document that can be associated with equipment to describe any sort of
-- restrictions compared with the original manufacturer's specification or
-- with the usual operational practice e.g. temporary maximum loadings, maximum
-- switching current, do not operate if bus couplers are open, etc.
-- In the UK, for example, if a breaker or switch ever mal-operates, this
-- is reported centrally and utilities use their asset systems to identify
-- all the installed devices of the same manufacturer's type. They then apply
-- operational restrictions in the operational systems to warn operators of
-- potential problems. After appropriate inspection and maintenance, the operational
-- restrictions may be removed.
CREATE TABLE "OperationalRestriction"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE
);

-- Operational tag placed on a power system resource or asset in the context
-- of switching plan execution or other work in the field.
CREATE TABLE "OperationalTag"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE
);

-- Document describing details of an active or planned outage in a part of
-- the electrical network.
-- A non-planned outage may be created upon:
-- - a breaker trip,
-- - a fault indicator status change,
-- - a meter event indicating customer outage,
-- - a reception of one or more customer trouble calls, or
-- - an operator command, reflecting information obtained from the field crew.
-- Outage restoration may be performed using a switching plan which complements
-- the outage information with detailed switching activities, including the
-- relationship to the crew and work.
-- A planned outage may be created upon:
-- - a request for service, maintenance or construction work in the field,
-- or
-- - an operator-defined outage for what-if/contingency network analysis.
CREATE TABLE "Outage"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE
);

-- Event recording the change in operational status of a power system resource
-- (PSR); may be for an event that has already occurred or for a planned activity.
CREATE TABLE "PSREvent"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE
);

-- Classifying instances of the same class, e.g. overhead and underground
-- ACLineSegments. This classification mechanism is intended to provide flexibility
-- outside the scope of this document, i.e. provide customisation that is
-- non standard.
CREATE TABLE "PSRType"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE
);

-- Common type for per-length impedance electrical catalogues.
CREATE TABLE "PerLengthImpedance"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE
);

-- Value associated with Equipment is used as compare.
CREATE TABLE "PinEquipment"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE
);

-- An electrical device designed to respond to input conditions in a prescribed
-- manner and after specified conditions are met to cause contact operation
-- or similar abrupt change in associated electric control circuits, or simply
-- to display the detected condition. Protection equipment is associated with
-- conducting equipment and usually operate circuit breakers.
CREATE TABLE "ProtectionEquipment"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE
);

-- Protective actions on non-switching equipment. The operating condition
-- is adjusted.
CREATE TABLE "ProtectiveActionAdjustment"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE
);

-- Protective action to put an Equipment in-service/out-of-service.
CREATE TABLE "ProtectiveActionEquipment"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE
);

-- A reporting group is used for various ad-hoc groupings used for reporting.
CREATE TABLE "ReportingGroup"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE
);

-- A collection of equipment for purposes other than generation or utilization,
-- through which electric energy in bulk is passed for the purposes of switching
-- or modifying its characteristics.
CREATE TABLE "Substation"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE
);

-- State variable for status.
CREATE TABLE "SvStatus"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE
);

-- An AC electrical connection point to a piece of conducting equipment. Terminals
-- are connected at physical connection points called connectivity nodes.
CREATE TABLE "Terminal"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE
);

-- Logical or physical point in the network to which readings or events may
-- be attributed. Used at the place where a physical or virtual meter may
-- be located; however, it is not required that a meter be present.
CREATE TABLE "UsagePoint"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE
);

-- Verification of a switch position or other condition as a switching step
CREATE TABLE "VerificationAction"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE
);

-- A collection of equipment at one common system voltage forming a switchgear.
-- The equipment typically consists of breakers, busbars, instrumentation,
-- control, regulation and protection devices as well as assemblies of all
-- these.
CREATE TABLE "VoltageLevel"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE,
    -- The bus bar's high voltage limit.
    -- The limit applies to all equipment and nodes contained in a given VoltageLevel.
    -- It is not required that it is exchanged in pair with lowVoltageLimit. It
    -- is preferable to use operational VoltageLimit, which prevails, if present.
    "highVoltageLimit" DOUBLE PRECISION,
    -- The bus bar's low voltage limit.
    -- The limit applies to all equipment and nodes contained in a given VoltageLevel.
    -- It is not required that it is exchanged in pair with highVoltageLimit.
    -- It is preferable to use operational VoltageLimit, which prevails, if present.
    "lowVoltageLimit" DOUBLE PRECISION,
    -- The base voltage used for all equipment within the voltage level.
    "BaseVoltage"CHAR VARYING(30),
    -- The substation of the voltage level.
    "Substation"CHAR VARYING(30)
);

-- This represents a source of ambient temperature.
CREATE TABLE "WeatherStation"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE
);

-- Wire spacing data that associates multiple wire positions with the line
-- segment, and allows to calculate line segment impedances. Number of phases
-- can be derived from the number of associated wire positions whose phase
-- is not neutral.
CREATE TABLE "WireSpacingInfo"
(
    "mRID" CHAR VARYING(30) NOT NULL UNIQUE
);

-- association constraint
ALTER TABLE "ACLineSegment" ADD FOREIGN KEY ( "AssetDatasheet" ) REFERENCES "AssetInfo" ( "mRID" );
-- association constraint
ALTER TABLE "ACLineSegment" ADD FOREIGN KEY ( "BaseVoltage" ) REFERENCES "BaseVoltage" ( "mRID" );
-- association constraint
ALTER TABLE "ACLineSegment" ADD FOREIGN KEY ( "EquipmentContainer" ) REFERENCES "EquipmentContainer" ( "mRID" );
-- association constraint
ALTER TABLE "ACLineSegment" ADD FOREIGN KEY ( "GroundingAction" ) REFERENCES "GroundAction" ( "mRID" );
-- association constraint
ALTER TABLE "ACLineSegment" ADD FOREIGN KEY ( "InstanceSet" ) REFERENCES "InstanceSet" ( "mRID" );
-- association constraint
ALTER TABLE "ACLineSegment" ADD FOREIGN KEY ( "JumpingAction" ) REFERENCES "JumperAction" ( "mRID" );
-- association constraint
ALTER TABLE "ACLineSegment" ADD FOREIGN KEY ( "LineGroundingAction" ) REFERENCES "GroundAction" ( "mRID" );
-- association constraint
ALTER TABLE "ACLineSegment" ADD FOREIGN KEY ( "LineJumpingAction" ) REFERENCES "JumperAction" ( "mRID" );
-- association constraint
ALTER TABLE "ACLineSegment" ADD FOREIGN KEY ( "Location" ) REFERENCES "Location" ( "mRID" );
-- association constraint
ALTER TABLE "ACLineSegment" ADD FOREIGN KEY ( "Outage" ) REFERENCES "Outage" ( "mRID" );
-- association constraint
ALTER TABLE "ACLineSegment" ADD FOREIGN KEY ( "PerLengthImpedance" ) REFERENCES "PerLengthImpedance" ( "mRID" );
-- association constraint
ALTER TABLE "ACLineSegment" ADD FOREIGN KEY ( "PropertiesCIMDataObject" ) REFERENCES "ChangeSetMember" ( "mRID" );
-- association constraint
ALTER TABLE "ACLineSegment" ADD FOREIGN KEY ( "PSRType" ) REFERENCES "PSRType" ( "mRID" );
-- association constraint
ALTER TABLE "ACLineSegment" ADD FOREIGN KEY ( "WireSpacingInfo" ) REFERENCES "WireSpacingInfo" ( "mRID" );
-- association constraint
ALTER TABLE "AnalogLimit" ADD FOREIGN KEY ( "LimitSet" ) REFERENCES "AnalogLimitSet" ( "mRID" );
-- association constraint
ALTER TABLE "Cut" ADD FOREIGN KEY ( "ACLineSegment" ) REFERENCES "ACLineSegment" ( "mRID" );
-- association constraint
ALTER TABLE "Equipment" ADD FOREIGN KEY ( "EquipmentContainer" ) REFERENCES "EquipmentContainer" ( "mRID" );
-- association constraint
ALTER TABLE "Fault" ADD FOREIGN KEY ( "Location" ) REFERENCES "Location" ( "mRID" );
-- association constraint
ALTER TABLE "Fault" ADD FOREIGN KEY ( "Outage" ) REFERENCES "Outage" ( "mRID" );
-- subclass-superclass constraint
ALTER TABLE "LineFault" ADD FOREIGN KEY ( "mRID" ) REFERENCES "Fault" ( "mRID" );
-- subclass-superclass constraint
ALTER TABLE "ProtectionEquipment" ADD FOREIGN KEY ( "mRID" ) REFERENCES "Equipment" ( "mRID" );
-- subclass-superclass constraint
ALTER TABLE "VoltageLevel" ADD FOREIGN KEY ( "mRID" ) REFERENCES "EquipmentContainer" ( "mRID" );
-- association constraint
ALTER TABLE "VoltageLevel" ADD FOREIGN KEY ( "BaseVoltage" ) REFERENCES "BaseVoltage" ( "mRID" );
-- association constraint
ALTER TABLE "VoltageLevel" ADD FOREIGN KEY ( "Substation" ) REFERENCES "Substation" ( "mRID" );
-- subclass-superclass constraint
ALTER TABLE "WireSpacingInfo" ADD FOREIGN KEY ( "mRID" ) REFERENCES "AssetInfo" ( "mRID" );
